---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  tasks:
  - name: Ansible create file with content example
    win_file:
      path: C:\abc.txt
      state: touch
  - name: Copy file to Win Server
    win_copy:
      src: /root/hlit_him/rpm_repo/Temp_CanDelete.txt
      dest: c:\temp\