---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  tasks:
  - name: Ansible create file with content example
    win_file:
      path: C:\shanky.txt
      state: touch
  - name: Restart machine
    win_reboot:
      shutdown_timeout_sec: 3600
      reboot_timeout_sec: 3600
- name: Again create a file
    win_file:
      path: C:\shashank.txt
      state: touch