---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  vars:
    my_url: "{{ version }}"
  tasks:
  - name: Ansible create file with content example
    win_file:
      path: C:\abc.txt
      state: touch
#  - name: Copy build to Windows Server
#    win_get_url:
#      url: ftp://Indiaqa@ftp.harmonicinc.com/Shashank_DLL
#      dest: c:\temp\
#      url_username: indiaQA
#      url_password: 4qAprsnt
#    register: get_url_result
#  - name: Ansible Delete Directory
#    win_file:
#      path: C:\Temp\NMX
#      state: absent
  - name: Download file from FTP with authentication
    win_get_url:
      url: "http://hivy/artifactory/ivy-repos/harmonic/nmx/{{version}}/{{build_number}}/nmx_build_output.zip"
      dest: c:\temp\
      url_username: "{{username}}"
      url_password: "{{password}}"
  - name: Unzip a bz2 (BZip) file
    win_unzip:
      src: c:\temp\nmx_build_output.zip
      dest: C:\temp\
#      creates: C:\temp\NMX
#  - name: Copy file to Win Server
#    win_copy:
#      src: "{{url}}"
#      dest: c:\temp\
#    register: win_copy_result
#  - name: Copy file to Win Server
#    win_copy:
#      #src: /usr/include/python2.7/pyconfig-64.h
#      src: /usr/include/python2.7/Temp.txt
#      dest: c:\temp\ 
# working url : ftp://Indiaqa@ftp.harmonicinc.com/HATS_installer.zip
#url_username: indiaQA
#url_password: 4qAprsnt