---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  tasks:
  - name: Ansible create file with content example
    win_file:
      path: C:\abc.txt
      state: touch
#  - name: Copy build to Windows Server
#    win_get_url:
#      url: ftp://Indiaqa@ftp.harmonicinc.com/Shashank_DLL
#      dest: c:\temp\
#      url_username: indiaQA
#      url_password: 4qAprsnt
#    register: get_url_result
#  - name: Ansible Delete Directory
#    win_file:
#      path: C:\Temp\NMX
#      state: absent
#  - name: Download file from FTP with authentication
#    win_get_url:
#      url: sftp://root@10.21.10.92/root/anaconda-ks.cfg
#      dest: c:\temp\
#      url_username: root
#      url_password: Pixel!@#
#    register: get_url_result
  - name: Copy file to Win Server
    win_copy:
      src: /usr/include/python2.7
      dest: c:\temp\
#  - name: Copy file to Win Server
#    win_copy:
#      #src: /usr/include/python2.7/pyconfig-64.h
#      src: /usr/include/python2.7/Temp.txt
#      dest: c:\temp\ 
# working url : ftp://Indiaqa@ftp.harmonicinc.com/HATS_installer.zip
#url_username: indiaQA
#url_password: 4qAprsnt