---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
  - name: Ansible find file
    win_find:
      paths: C:\temp\NMX-A
      patterns: ['*.txt']
      recurse: True
    register: resultFile
  - name: Ansible create file with content example
    win_file:
      path: "{{resultFile.files[0].path}}"
      state: absent
