---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  tasks:
  - name: Ansible create file with content example
    win_file:
      path: C:\abc.txt
      state: touch
  - name: Add block in file
    blockinfile:
      path: C:\abc.txt
      block: |
        These lines are added by blockinfile module
        Check out the marker lines
      backup: yes