---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required

    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present