---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
  - name: Download file from FTP with authentication
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion
      name: CommonFilesDir
    register: common_files_dir
  - debug:
    var: common_files_dir.value
  - debug:
    var: common_files_dir
  - debug:
    var: CommonFilesDir