---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- hosts: all
  tasks:
  - name: Ansible create file with content example
    copy:
      dest: "c:/remote_server.txt"
      content: |
        dog1
        tiger