---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
  - name: Ping ip
    win_wait_for:
      host: "{{ ansible_host }}"
      port: "{{ansible_port}}" #SSH Port
      delay: 60 # wait 1 minute before trying
  - name: Find the installation file
    win_find:
      paths: C:\Temp\nmx
      patterns: ['*.exe']
      recurse: True
    register: resultFile